### ISSUE TITLE
Archiver les anciens chapitres

### ISSUE THREAD

**Issue by Nailseater** [mparpaillon/harpy-feedback#11]
Il faudrait la possibilité d'archiver pour le MJ les chapitres qui ne sont plus joués ou du moins ne pas les avoir dans cette barre là. Je pense que s'il y a beaucoup d'apparter ça peut vite devenir le bordel si les chapitres restent tous visibles.

![e176d0b59bf6f6940df2c2af96d15929](https://user-images.githubusercontent.com/58190293/70046481-704ca300-15c6-11ea-868b-fa1adc9d5391.png)

**Comment by mparpaillon** [comment]
Fixed in 2.18.0
