### ISSUE TITLE
[BUG] Illustration - Edition d'un chapitre 

### ISSUE THREAD

**Issue by Nailseater** [mparpaillon/harpy-feedback#15]
"Quand on édite un chapitre, il faut chaque fois remettre l'illustration. 
Même si on veut juste changer le nom du chapitre.
Quand j'édite, ça me remet l'image du pré verdoyant. 
Et ça me vire l'image perso. Même si je touche que au nom."

**Comment by mparpaillon** [comment]
Enfin corrigéééé ! (dans la 3.0.0)
