### ISSUE TITLE
Filtres dans la barre de recherche

### ISSUE THREAD

**Issue by Nailseater** [mparpaillon/harpy-feedback#25]
Quand on crée plusieurs NPCs à la suite, les recherches pour les images restent enregistrées, mais ne filtrent pas les images.

Exemple : j'ai créé un NPC "Orc Moche" (je n'ai pas de coeur) et quand je clique sur ajouter un autre NPC, la recherche pour "orc" est toujours là. Les images ne sont cependant pas filtrées.

**Comment by mparpaillon** [comment]
Fixed in 2.9.0
