### ISSUE TITLE
trop de chapitres actifs = on ne peut plus scroll jusqu'en bas. 

### ISSUE THREAD

**Issue by Nailseater** [mparpaillon/harpy-feedback#27]
Sous firefox seulement

Bug qui bloque le jeu entièrement :

Quand on a trop de chapitres actifs, on ne peut plus scroll jusqu'en bas. 
Screens pour expliquer 👍

Ca, c'est ce que j'avais avant. Comme on a fait planter deux chapitres (merci @Salazard :heart: ) j'en ai créé d'autres.

![1](https://user-images.githubusercontent.com/58190293/70262535-d0913f80-1794-11ea-934d-09683d6a5851.png)

Maintenant que j'ai deux chapitres supplémentaires, j'ai ceci :

![2](https://user-images.githubusercontent.com/58190293/70262561-dc7d0180-1794-11ea-86be-b8a6fc5521df.png)

Et impossible de scroll plus bas.
Donc je pense que c'est lié aux chapitres dans la colonne de gauche
Je vais ajouter un chapitre pour voir

![unknown (1)](https://user-images.githubusercontent.com/58190293/70262603-f3bbef00-1794-11ea-813f-7dfd262f76fc.png)

Je confirme, je n'ai même plus accès à la barre de dialogue. ^^

**Comment by mparpaillon** [comment]
Fixed in 2.11.0
