### ISSUE TITLE
Fusion de stories portant le même nom

### ISSUE THREAD

**Issue by Nailseater** [mparpaillon/harpy-feedback#29]
J'ai créer une story Test dans le monde Test, alors que je joue déjà dans une story test avec le monde test. Et les deux semblent se mélanger dans la gestion des chapitres (voir screen)
Le problème se poserait si une personne joue ou MJ sur plusieurs tables d'un même univers. Exemple : DnD, il y aurait alors plusieurs chapitre 1 présents.

![Capture_decran_2019-12-05_a_16 28 58](https://user-images.githubusercontent.com/58190293/70262839-5ad9a380-1795-11ea-9c24-b881a842c442.png)

**Comment by mparpaillon** [comment]
Fixed in 2.7.0
