### ISSUE TITLE
Disfonctionnement du crop

### ISSUE THREAD

**Issue by rparpaillon** [mparpaillon/harpy-feedback#30]
Lors de la création du personnage, il arrive que le crop ne fonctionne pas via "Chrome". La validation ne marche pas tout le temps. Après avoir compris le souci, il s'avère que l'indication de validation lié à l'image n'avait pas été comprise par le joueur. 
Revoir l'ergonomie.

**Comment by mparpaillon** [comment]
Fixed in 2.8.0
