### ISSUE TITLE
Mauvais personnage

### ISSUE THREAD

**Issue by rparpaillon** [mparpaillon/harpy-feedback#33]
Il arrive que le MJ se retrouve à parler avec un personnage qui n'est pas le sien. Problème reconnu par Edzart.

"15:31] Edzart: Là, je parlais avec Orc Moche et c'est Sam Gamejay qui a dit le message suivant. ^^
[15:31] Edzart: Ensuite, j'ai écrit test avec l'orc et au troisième, c'est passé sur Sam Gamejay"

https://media.discordapp.net/attachments/642708126360928256/652154890948313098/unknown.png?width=899&height=703

**Comment by mparpaillon** [comment]
FIxed in 2.7.0
