### ISSUE TITLE
Problème de scrolling

### ISSUE THREAD

**Issue by rparpaillon** [mparpaillon/harpy-feedback#34]
Lorsqu'il y a trop de chapitres, il arrive que le scrolling se bloque. Le souci a été rencontré par Erzart.

https://media.discordapp.net/attachments/642708126360928256/652168824052908045/unknown.png?width=1187&height=605

https://media.discordapp.net/attachments/642708126360928256/652169022095360010/unknown.png?width=1187&height=607

Du coup il ne peut plus scroll.

https://media.discordapp.net/attachments/642708126360928256/652169446240157696/unknown.png?width=1187&height=606

**Comment by mparpaillon** [comment]
Duplicate
