### ISSUE TITLE
Suppression de message bugué

### ISSUE THREAD

**Issue by rparpaillon** [mparpaillon/harpy-feedback#38]
Voici le bug relevé par Galactur 👍 

"j'ai supprimé des messages du canal rp (qui n'étaient pas rp du coup) à la chaîne, et ça a commencé à me dédoubler des messages déjà existant. J'avais par exemple la présentation de vos persos en triple exemplaire, j'ai testé d'en supprimer une, mais en rafraichissant ça l'a enlevée tout simplement. "

**Comment by mparpaillon** [comment]
Non reproduit.
