### ISSUE TITLE
Problème lié à l'invitation

### ISSUE THREAD

**Issue by rparpaillon** [mparpaillon/harpy-feedback#41]
Sous "Edge", la notification liée à une invitation pour un groupe apparaît mais lorsque l'on clique sur celle-ci rien n'apparait pas ! 
Problème rencontré par Grayfox.

https://cdn.discordapp.com/attachments/642708126360928256/652930052790550548/unknown.png

**Comment by mparpaillon** [comment]
Problème pas lié à Edge à priori. Grayfox a eu des problèmes avec son ancien compte. Je close pour l'instant en attendant un moyen de reproduire ce bug
