### ISSUE TITLE
Suppression d'invitation suite à la modification du pseudo

### ISSUE THREAD

**Issue by rparpaillon** [mparpaillon/harpy-feedback#42]
Commentaire discord:
"Quand j’ai crée mon compte Tales, j’ai obtenu un pseudo par défaut, du nom de ProfessorJustice. J’ai par la suite crée mon personnage et je me suis fait inviter dans la partie de @Mondoroin / AbirCaes  puis dans le chapitre.

Cependant, pendant ce laps de temps d’invitation, j’ai modifié le pseudo de mon compte en « Wawaex »
Et je n’ai toujours pas accès au chapitre"

https://cdn.discordapp.com/attachments/642708126360928256/653338914785984536/image0.jpg

Apparemment si tu viens à modifier ton pseudo au même moment que la reception de l'invitation, cette dernière s'annule !

Vu avec Maslow et Wawaex

**Comment by mparpaillon** [comment]
Non reproduit.

**Comment by mparpaillon** [comment]
Fixed 2.11.0 (probably)
