### ISSUE TITLE
Noms et textes trop longs

### ISSUE THREAD

**Issue by rparpaillon** [mparpaillon/harpy-feedback#48]
https://media.discordapp.net/attachments/642708126360928256/654235615742787615/received_559542041274007.png?width=1187&height=119

Maslow: Hum
Maslow: Faut que je limite aussi le nom du perso ?
Edzart: Si on écrit trop dans la didascalie, ça part en sucette !
Edzart: XD
Maslow: Si tu mets des espaces ça ira très bien
Edzart: Ah ?
Maslow: j'ajouterai un break-word
_Salazard: Alors niveau du nom je dirait 140 char, Shortname 100 char, et description 200_

limiter le nombre de caractère à 140 pour le nom, 100 pour le shortname et 200 pour la description MAX.

https://media.discordapp.net/attachments/642708126360928256/654265775389016074/Capture_decran_2019-12-11_a_11.18.02.png?width=322&height=703

https://media.discordapp.net/attachments/642708126360928256/654267424647938059/Capture_decran_2019-12-11_a_11.24.56.png

**Comment by mparpaillon** [comment]
Fixed in 2.12.0

J'ai mis 40 - 20 - 40
Donc pas du tout ce qu'avait dit Salazard. C'était beaucoup trop
