### ISSUE TITLE
Scroll impossible si trop de persos

### ISSUE THREAD

**Issue by rparpaillon** [mparpaillon/harpy-feedback#49]
11:32] Salazard: Il semble impossible de scroll dans la liste des personnages (Chrome). De plus je ne comprend pas bien l'ordre des persos.
Il semble y avoir : 
- les nombres 1-9 ...
- les char en majuscule
- les char en minuscule

https://media.discordapp.net/attachments/642708126360928256/654269172662140928/Capture_decran_2019-12-11_a_11.30.13.png?width=1187&height=600

**Comment by mparpaillon** [comment]
Fixed in 2.12.0
