### ISSUE TITLE
Souci "Responsive" au niveau de l'overlay du choix des stories

### ISSUE THREAD

**Issue by rparpaillon** [mparpaillon/harpy-feedback#61]
10:46] grayfoxliquid: 

Sur mobile, quand on est focus sur le hrp et qu'on appuie sur le Logo TALES en haut à gauche , l'overlay du choix des stories s'ouvre quand même au-dessus du RP. 
Du coup on voit juste l'écran qui s'assombrit un peu. J'ai mis trop longtemps à me rendre compte que c'était à cause de l'overlay qui s'ouvrait à gauche xD

**Comment by mparpaillon** [comment]
Fixed in 3.0.0
