### ISSUE TITLE
 nom des personnages des joueurs invités sur le serveur 

### ISSUE THREAD

**Issue by Nailseater** [mparpaillon/harpy-feedback#62]
Il faudrait avoir un moyen d'avoir le nom des personnages des joueurs qu'on a invité sur le serveur parce que actuellement, à part si il te le donne en mp, tu ne peux pas l'ajouter comme Character au chapitre. (Le nom du compte ne marche pas et dans Settings, il n'y a que cette info.)

**Comment by mparpaillon** [comment]
On peut désormais directement sélectionner les PJ. L'autocomplete ne sert qu'aux PNJ

<img width="604" alt="Capture d’écran 2020-02-11 à 10 02 01" src="https://user-images.githubusercontent.com/1062115/74222802-8efda300-4cb5-11ea-8054-b16e739821cc.png">
