### ISSUE TITLE
MJ absent pour les invitations

### ISSUE THREAD

**Issue by rparpaillon** [mparpaillon/harpy-feedback#74]
[14:08]  Edzart:
https://cdn.discordapp.com/attachments/642708126360928256/677863749779980318/Screenshot_2020-02-14-14-08-00-119_com.android.chrome.png

[14:08]  Edzart: J'ai pas la MJ dans les propositions de personnes avec qui créer un groupe

**Comment by mparpaillon** [comment]
Fixed in 3.0.1 (vu que seul le MJ peut créer un chat maintenant)
