### ISSUE TITLE
Milestone au meme niveau 

### ISSUE THREAD

**Issue by rparpaillon** [mparpaillon/harpy-feedback#77]
17:40]  grayfoxliquid: Sinon, la barre du Milestone est juste 5-10 pixels plus grand que la partie écriture, du coup ça fait un petit changement quand on passe de l'un à l'autre. C'est un détail, mais ça peut être sympa de les avoir à la même taille ^^

**Comment by mparpaillon** [comment]
Fixed in 3.0.1
