### ISSUE TITLE
[Zayne] Harpy Tag not updated when changed

### ISSUE THREAD

**Issue by tc-nwaucheul** [mparpaillon/harpy-feedback#90]
In the profile page, when a user change his Harpy Tag and hit "save", the new Tag is saved into Firebase but the change is not reflected on the profile page until user refresh the page.

Steps to reproduce: 
- Go to profile page and click "update profile" icon
- Update Harpy Tag
- Click "save"

Expected behavior: 
- Harpy Tag should be updated

Actual behavior: 
- Should update Harpy Tag right away

**Comment by mparpaillon** [comment]
Fixed in commit d0b6212ddef20b1f715b3b3f9cdc6305c5670004

**Comment by mparpaillon** [comment]
Test d0b6212ddef20b1f715b3b3f9cdc6305c5670004
